version: '3'

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - TZ=America/New_York
      - HOSTNAME="PlexServer"
      - PLEX_LOG_LEVEL=debug
      - VERSION=docker
    volumes:
      - ./docker/plex/config:/config
      - ./docker/plex/transcode:/transcode
      - ./media:/data
    ports:
      - "32400:32400"
    restart: unless-stopped
